Dash/Dash/urls.py
from django.contrib import admin
from django.urls import include, re_path, path
from django.shortcuts import redirect
#from dashboard.views import mi_vista

appname ='dashboard'

urlpatterns = [
    path('', lambda request: redirect('dashboard/', permanent=False)),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),



]

Dash/dashboard/urls.py
#from django.conf.urls import url
from django.urls import path
#from . import views
from dashboard import views
from django.urls import re_path
from .views import *
from django.urls import include, path


app_name = 'dashboard'

urlpatterns = [
    #path('', views.index, name='index'),
    #path('',views.inicio,name='inicio',),

    ### Inicio ###
    path('', views.login_request, name="login"),
    path('logout.html', views.logout_view, name='logout'),


    path('index.html', index.as_view(), name='index'),



    #Paneles#

    path('panel_usuarios.html',panel_usuarios.as_view(),name ='panel_usuarios'),
    path('panel_telefonos.html',panel_telefonos.as_view(),name ='panel_telefonos'),
    path('panel_smartphones.html',panel_smartphones.as_view(),name ='panel_smartphones'),
    path('panel_tablets.html',panel_tablets.as_view(),name ='panel_tablets'),
    path('panel_notebooks.html',panel_notebooks.as_view(),name ='panel_notebooks'),
    path('panel_camionetas.html',panel_camionetas.as_view(),name ='panel_camionetas'),
    path('panel_asginacion.html',panel_asignacion.as_view(),name ='panel_asignacion'),
    path('panel_modelos.html',panel_modelos.as_view(),name ='panel_modelos'),
    path('panel_procesadores.html',panel_procesadores.as_view(),name ='panel_procesadores'),
    path('panel_marcas.html',panel_marcas.as_view(),name ='panel_marcas'),
    path('panel_mantencion.html',panel_mantenciones.as_view(),name ='panel_mantencion'),
    path('mantencion/<int:pk>', views.listado_mantenciones.as_view(), name = 'mantenciones'),
    path('usuarios/<int:pk>', views.reporte.as_view(), name = 'reporte'),
    path('reporte/<int:pk>/imprimir/', imprimir_reporte, name='imprimir_reporte'),




    ### Usuarios ###
    path('usuario/<str:pk>', detalle_usuario.as_view(), name='userdetail'),
    path('usuario/form/', crear_usuario.as_view(), name='newuser'),
    path('usuario/update/<str:pk>', actualizar_usuario.as_view(), name='edituser'),
    path('usuario/delete/<str:pk>', borrar_usuario.as_view(), name='deleteuser'),
    path('usuarios/<int:pk>/imprimir_reporte/', imprimir_reporte, name='imprimir_reporte'),


    ### Telefonos ###
    path('telefonos/<str:pk>', detalle_telefono.as_view(), name ='teldetail'),
    path('telefonos/form/', crear_telefono.as_view(), name = 'newtel'),
    path('telefonos/update/<str:pk>', actualizar_telefono.as_view(), name= 'edittel'),
    path('telefonos/delete/<str:pk>', borrar_telefono.as_view(), name = 'deletetel'),

    ### Smartphones ###
    path('smartphones/<str:pk>', detalle_smartphone.as_view(), name ='smadetail'),
    path('smartphones/form/', crear_smartphone.as_view(), name = 'newsma'),
    path('smartphones/update/<str:pk>', actualizar_smartphone.as_view(), name= 'editsma'),
    path('smartphones/delete/<str:pk>', borrar_smartphone.as_view(), name = 'deletsma'),

    ### Tablets ###
    path('tablets/<str:pk>', detalle_tablet.as_view(), name ='tadetail'),
    path('tablets/form/', crear_tablet.as_view(), name = 'newta'),
    path('tablets/update/<str:pk>', actualizar_tablet.as_view(), name= 'edita'),
    path('tablets/delete/<str:pk>', borrar_tablet.as_view(), name = 'deleta'),

    ### Notebooks ###
    path('notebooks/<str:pk>', detalle_notebook.as_view(), name ='notdetail'),
    path('notebooks/form/', crear_notebook.as_view(), name = 'newnot'),
    path('notebooks/update/<str:pk>', actualizar_notebook.as_view(), name= 'editnot'),
    path('notebooks/delete/<str:pk>', borrar_notebook.as_view(), name = 'deletnot'),

    ### Camionetas ###
    path('camionetas/<str:pk>', detalle_camioneta.as_view(), name ='camdetail'),
    path('camionetas/form/', crear_camioneta.as_view(), name = 'newcam'),
    path('camionetas/update/<str:pk>', actualizar_camioneta.as_view(), name= 'editcam'),
    path('camionetas/delete/<str:pk>', borrar_camioneta.as_view(), name = 'deletcam'),

    ### Asignaciones ###
    path('asignacion/<str:pk>', detalle_asignacion.as_view(), name ='asgdetail'),
    path('asignacion/form/', crear_asignacion.as_view(), name = 'newasg'),
    path('asignacion/update/<str:pk>', actualizar_asignacion.as_view(), name= 'editasg'),
    path('asignacion/delete/<str:pk>', borrar_asignacion.as_view(), name = 'deletasg'),

        ### Modelos ###
    path('modelos/<str:pk>', detalle_modelo.as_view(), name ='moddetail'),
    path('modelos/form/', crear_modelo.as_view(), name = 'newmod'),
    path('modelos/update/<str:pk>', actualizar_modelo.as_view(), name= 'editmod'),
    path('modelos/delete/<str:pk>', borrar_modelo.as_view(), name = 'deletmod'),

        ### Procesador ###
    path('procesador/<str:pk>', detalle_procesador.as_view(), name ='prodetail'),
    path('procesador/form/', crear_procesador.as_view(), name = 'newpro'),
    path('procesador/update/<str:pk>', actualizar_procesador.as_view(), name= 'editpro'),
    path('procesador/delete/<str:pk>', borrar_procesador.as_view(), name = 'deletpro'),

        ### Marcas ###
    path('marcas/<str:pk>', detalle_marca.as_view(), name ='madetail'),
    path('marcas/form/', crear_marca.as_view(), name = 'newma'),
    path('marcas/update/<str:pk>', actualizar_marca.as_view(), name= 'editma'),
    path('marcas/delete/<str:pk>', borrar_marca.as_view(), name = 'deletma'),

        ### Mantenciones ###
    path('mantencion/<str:pk>', detalle_mantencion.as_view(), name ='mantedetail'),
    path('mantencion/form/', crear_mantencion.as_view(), name = 'newmante'),
    path('mantencion/update/<str:pk>', actualizar_mantencion.as_view(), name= 'editmante'),
    path('mantencion/delete/<str:pk>', borrar_mantencion.as_view(), name = 'deletmante'),

    path('cargar_excel/', cargar_excel, name='cargar_excel'),
    path('doom/', jugar_doom, name='doom'),
    ### Series ###
#    path('series/<str:pk>', detalle_serie.as_view(), name='seriedetail'),
#    path('series/form/', crear_serie.as_view(), name='newserie'),
#    path('series/update/<str:pk>', actualizar_serie.as_view(), name= 'editserie'),
#    path('series/delete/<str:pk>', borrar_serie.as_view(), name= 'deleteserie'),


]

Dash/dashboard/views.py
from audioop import reverse
from re import U
from tokenize import Single
from typing import List
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import View
from .models import Usuarios
from django.shortcuts import render
from .forms import *
from . import views
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView,UpdateView,DeleteView)
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import pdfkit
from django.template.loader import get_template
import base64
import openpyxl
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from datetime import date, datetime, timedelta


#@login_required
#def inicio(request):
#    """
#     Página inicial del sitio
#    :param request: Django request
#    :return: Html
#    """
#    ctx = {}
#
#    return render(
#        request,
#        'directorio/inicio.html',
#        ctx
#    )

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("dashboard:index")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(
            request=request,
            template_name="dashboard/login.html",
            context={"login_form":form})

def logout_view(request):
    logout(request)
    return redirect('/dashboard') # replace 'login' with the URL name of your login page

@method_decorator(login_required, name='dispatch' )
class index(ListView):  
    context_object_name = 'index'
    template_name = 'dashboard/index.html'
    queryset = Usuarios.objects.all()

    def get_context_data(self, **kwargs):
        context = super(index, self).get_context_data(**kwargs)

        ### Contadores de Smartphones ###
        context['total_smartphones'] = Smartphones.objects.count()
        context['assigned_smartphones'] = Asignacion.objects.filter(smartphone_a__estado_telefono=True, vigente=True).count()
        context['unusable_smartphones'] = Smartphones.objects.filter(estado_telefono=False).count()
        context['available_smartphones'] = context['total_smartphones'] - context['assigned_smartphones'] - context ['unusable_smartphones']
        ###Contadores de Notebooks ####
        context['total_notebooks'] = Notebooks.objects.count()
        context['assigned_notebooks'] = Asignacion.objects.exclude(notebook_a=None).exclude(vigente=False).count()
        context['unusable_notebooks'] = Notebooks.objects.filter(estado_notebook=False).count()
        context['available_notebooks'] = context['total_notebooks'] - context['assigned_notebooks'] - context['unusable_notebooks']
        ### Contadores de Tablets###
        context['total_tablets'] = Tablets.objects.count()
        context['assigned_tablets'] = Asignacion.objects.exclude(tablet_a=None).exclude(vigente=False).count()
        context['unusable_tablets'] = Tablets.objects.filter(estado_tablet=False).count()
        context['available_tablets'] = context['total_tablets'] - context['assigned_tablets'] - context['unusable_tablets']
        ### Contadores de camionetas ###
        context['total_camionetas'] = Camionetas.objects.count()
        context['assigned_camionetas'] = Asignacion.objects.exclude(camionetas_a=None).exclude(vigente=False).count()
        context['unusable_camionetas'] = Camionetas.objects.filter(disponible=False).count()
        context['available_camionetas'] = context['total_camionetas'] - context['assigned_camionetas'] - context['unusable_camionetas']

        threshold_date = date.today() - timedelta(days=365)
        context['notebooks_for_maintenance'] = Notebooks.objects.filter(mantencion_notebook__lte=threshold_date)
        return context
        #return super().get_context_data(**kwargs)

##### Paneles de acceso ####

@method_decorator(login_required, name='dispatch')
class panel_usuarios(ListView):
    context_object_name = 'panel_usuarios'
    template_name = 'dashboard/panel_usuarios.html'
    paginate_by = 50
    search_form = SearchForm

    def get_queryset(self):
        queryset = Usuarios.objects.order_by('nombre')
        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(
                Q(nombre__icontains=query) |
                Q(apellido__icontains=query) |
                Q(rut__icontains=query) |
                Q(centro_de_costo__icontains=query) |
                Q(gerente__icontains=query) |
                Q(empresa__icontains=query)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(panel_usuarios, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form(self.request.GET or None)
        return context

@method_decorator(login_required, name='dispatch' )
class panel_telefonos(ListView):
    context_object_name = 'panel_telefonos'
    template_name = 'dashboard/panel_telefonos.html'
    paginate_by = 50
    search_form = SearchForm
    
    def get_queryset(self):
        queryset = Num_telefono.objects.order_by('numero_tel')
        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(
                Q(numero_tel__icontains=query) |
                Q(activo__icontains=query)
            )
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(panel_telefonos, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form(self.request.GET or None)
        return context

@method_decorator(login_required, name='dispatch' )
class panel_smartphones(ListView):
    context_object_name = 'panel_smartphones'
    template_name = 'dashboard/panel_smartphones.html'
    paginate_by = 50
    search_form = SearchForm

    def get_queryset(self):
        show_available = self.request.GET.get('show_available')
        queryset = Smartphones.objects.order_by('serie_smartphone')
        
        if show_available == 'true':
            available_devices = Asignacion.objects.filter(vigente=False).values_list('smartphone_a_id', flat=True)
            queryset = queryset.filter(
                Q(id__in=available_devices) |
                Q(asignacion__isnull=True)
            )

        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(
                Q(serie_smartphone__icontains=query) |
                Q(modelo_smartphone__m_modelo__icontains=query)  |
                Q(modelo_smartphone__m_marca__marca__icontains=query) |
                Q(modelo_smartphone__m_param__nombre_param__icontains=query) |
                Q(imei1__icontains=query) |
                Q(imei2__icontains=query) |
                Q(estado_telefono__icontains=query)  
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(panel_smartphones, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form(self.request.GET or None)

        return context
    
@method_decorator(login_required, name='dispatch' )
class panel_tablets(ListView):
    context_object_name = 'panel_tablets'
    template_name = 'dashboard/panel_tablets.html'
    paginate_by = 50
    search_form = SearchForm

    def get_queryset(self):
        show_available = self.request.GET.get('show_available')
        queryset = Tablets.objects.order_by('serie_tablet')

        if show_available == 'true':
            available_devices = Asignacion.objects.filter(vigente=False).values_list('tablet_a_id', flat=True)
            queryset = queryset.filter(
                Q(id__in=available_devices) |
                Q(asignacion__isnull=True)
            )

        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(
                Q(serie_tablet__icontains=query) |
                Q(modelo_tablet__m_modelo__icontains=query)  |
                Q(modelo_tablet__m_marca__marca__icontains=query)  |
                Q(modelo_tablet__m_param__nombre_param__icontains=query)  |
                Q(estado_tablet__icontains=query)  
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(panel_tablets, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form(self.request.GET or None)
        return context


@method_decorator(login_required, name='dispatch' )
class panel_notebooks(ListView):
    context_object_name = 'panel_notebooks'
    template_name = 'dashboard/panel_notebooks.html'
    paginate_by = 50
    search_form = SearchForm

    def get_queryset(self):
        show_available = self.request.GET.get('show_available')
        queryset = Notebooks.objects.order_by('serie_notebook')

        if show_available == 'true':
            available_devices = Asignacion.objects.filter(vigente=False).values_list('notebook_a_id', flat=True)
            queryset = queryset.filter(
                Q(id__in=available_devices) |
                Q(asignacion__isnull=True)
            )

Dash/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="es">
<html>
    <head>
        {% load static %}
            <!-- Header content goes here -->
            {% block title %} <title>Dashboard Curimapu</title>             {% endblock %}
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <script src="
            https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js
            "></script>
            <link href="
            https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css
            " rel="stylesheet">
            
            <!-- Add additional CSS in static file -->
  
            <style>
                body {
                    font-family: 'OpenSans-Light', sans-serif;
                    }
                .sidebar {
                    width: 12.5%; /* 1/8 of the total page width */
                    background-color: rgb(15, 23, 42); /* set the background color */
                    height: 100dvh; /* set the height to fill the viewport */
                    position: fixed; /* keep the sidebar fixed in place */
                    width: 10%;
                    top: 1; /* position the sidebar at the top of the viewport */
                    left: 0; /* position the sidebar at the left of the viewport */
                    z-index: 1; /* set the z-index to 1 to keep the sidebar above other content */
                }
                .navbar {
                    position: fixed;
                    top: 0;
                    left: 0%;
                    width: 100%;
                    height: 60px; /* add this line */
                    z-index: 1;
                }
                .nav-link {
                    color: #fff;
                }
                main {
                    margin-top: 60px; /* set the top margin to match the height of the navbar */
                    margin-left: 10.5%; /* set the left margin to match the width of the sidebar */
                    width: 88%; /* set the width to occupy the remaining space on the page */
                    padding-top: 20px; /* add padding to create space between the header and the main content */
                    z-index: 1;
                }
                .footer {
                    position: fixed;
                    left: 0;
                    bottom: 0;
                    width: 100%;
                    background-color: #333;
                    color: #fff;
                    text-align: center;
                    padding: 10px;
                    }
            </style>
    </head>
<body>
    <header>
        {% block header %}
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: rgb(30 41 59); z-index:2;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url "dashboard:index" %}">
                        <img src="{% static '/img/logocurimapu.png' %}" alt="Curimapu" width="250px" height="40px">
                </a>
                <div class ="d-flex justify-content-between">
                  <div class = "ml-auto">
                  <p style="color: white;">Bienvenido, {{ request.user.username }}</p>
                  <a href="{% url 'dashboard:logout' %}">Logout</a>
                </div>
              </div>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                  </ul>
                </div>
            </div>
        </nav>
        {% endblock %}
    </header>
    {% block side %}
    <div class="sidebar">
      <ul class="nav flex-column">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="usuariosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Usuarios
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-end" aria-labelledby="usuariosDropdown">
            <li><a class="dropdown-item" href="{% url "dashboard:panel_usuarios" %}">Trabajadores</a></li>
            <li><a class="dropdown-item" href="{% url "dashboard:panel_telefonos" %}">Numeros de telefono</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="equiposDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Equipos
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-end" aria-labelledby="equiposDropdown">
            <li><a class="dropdown-item" href="{% url "dashboard:panel_camionetas" %}">Camionetas</a></li>
            <li><a class="dropdown-item" href="{% url "dashboard:panel_tablets" %}">Tablets</a></li>
            <li><a class="dropdown-item" href="{% url "dashboard:panel_smartphones" %}">Smartphones</a></li>
            <li><a class="dropdown-item" href="{% url "dashboard:panel_notebooks" %}">Notebooks</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="datosMaestrosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Datos Maestros
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-end" aria-labelledby="datosMaestrosDropdown">
            <li><a class="dropdown-item" href="{% url "dashboard:panel_marcas" %}">Marcas</a></li>
            <li><a class="dropdown-item" href="{% url "dashboard:panel_modelos" %}">Modelos</a></li>
            <li><a class="dropdown-item" href="{% url "dashboard:panel_procesadores" %}">Procesadores</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "dashboard:panel_asignacion" %}">Asignacion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "dashboard:panel_mantencion" %}">Mantencion</a>
        </li>
      </ul>
    </div>
    {% endblock %}
    <nav>
        {% block nav %}
            <!-- Navigation menu goes here -->
        {% endblock %}
    </nav>
    <main>
        {% block content %}
            <!-- Main content goes here -->
        {% endblock %}
    </main>
    <footer>
        {% block footer %}
            <!-- Footer content goes here -->
            <footer>
                <div class="container">
                  <div class="row">
                  </div>
                </div>
              </footer>
        {% endblock %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

Dash/dashboard/templates/dashboard/listado_mantenciones.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block nav %}
    <!-- Custom navigation menu goes here -->
{% endblock %}
{% block content %}
<p>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'dashboard:newmante' %}'">Registrar</button>
</p>
<p>{{ dashboard.name }}</p>
<div class="card text-dark bg-light mb-3">
  <div class="card-body">
      <h5 class="card-title">Listado de mantenciones</h5>
      <div class="table-responsive" style="max-height: calc(100vh - 230px); overflow-y: auto;">
        <table class="table table-hover table-bordered">
            <thead style="background-color: rgb(25, 231, 227);">
            <tr>
                <th>Patente</th>
                <th>Fecha Mantencion</th>
                <th>Kilometraje aproximado</th>
                <th>Estado mantencion</th>
                <th>Responsable</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for Mantenciones in object_list %}
            <tr class="table-hover">
                <td>{{ Mantenciones.m_patente }}</td>
                <td>{{ Mantenciones.fecha_mantencion }}</td>
                <td>{{ Mantenciones.m_kilometraje }}</td>
                <td>{{ Mantenciones.m_estado }}</td>
                <td>{{ Mantenciones.responsable }}</td>
                <td><a href="{% url "dashboard:editmante" Mantenciones.pk %}" class="btn btn-warning btn-sm">Editar</a>
                    <a href="{% url "dashboard:deletmante" Mantenciones.pk %}" class="btn btn-danger btn-sm">Borrar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="pagination d-flex justify-content-between">
  <p>
    <a href="{% url "dashboard:panel_camionetas" %}" class="btn btn-secondary">Volver a camionetas</a>
</p>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page=1" class="page-link" aria-label="First">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
          <span aria-hidden="true">&lsaquo;</span>
        </a>
      </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
          <span aria-hidden="true">&rsaquo;</span>
        </a>
      </li>
        <li class="page-item">
          <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" aria-label="Last">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
  </ul>
    <p>
        <button type="button" class="btn btn-primary" onclick="location.href='{% url 'dashboard:newmante' %}'">Ingresar mantencion</button>
    </p>
</div>
</div>
{% endblock %}

Dash/dashboard/templates/dashboard/logout.html
Cerrado exitosamente

Dash/dashboard/templates/dashboard/usuario_form.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

Dash/dashboard/templates/dashboard/usuarioconfirmdelete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form> 